FROM php:8.2-apache

# Install dependency yang dibutuhkan MySQL
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    libmariadb-dev \
    && docker-php-ext-install pdo_mysql

# Aktifkan apache rewrite (optional tapi umum)
RUN a2enmod rewrite

# Copy source code
COPY . /var/www/html/

# Permission
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
