FROM php:8.2-cli

# 🔥 Install OS dependency untuk MySQL
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    libmysqlclient-dev \
    && docker-php-ext-install pdo pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080", "-t", "."]
